extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

processors:
  batch:
    timeout: 30s
  queued_retry:
  resourcedetection:
  resourcedetection/ec2:
    detectors: [env, ec2]
    timeout: 2s
    override: false

exporters:
  awsxray:
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry, resourcedetection/ec2]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [awsemf]

  extensions: [health_check]
